; Auto-generated. Do not edit!


(cl:in-package move_quadcopter-msg)


;//! \htmlinclude NavigateGoal.msg.html

(cl:defclass <NavigateGoal> (roslisp-msg-protocol:ros-message)
  ((target_pos
    :reader target_pos
    :initarg :target_pos
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass NavigateGoal (<NavigateGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move_quadcopter-msg:<NavigateGoal> is deprecated: use move_quadcopter-msg:NavigateGoal instead.")))

(cl:ensure-generic-function 'target_pos-val :lambda-list '(m))
(cl:defmethod target_pos-val ((m <NavigateGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_quadcopter-msg:target_pos-val is deprecated.  Use move_quadcopter-msg:target_pos instead.")
  (target_pos m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateGoal>) ostream)
  "Serializes a message object of type '<NavigateGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pos) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateGoal>) istream)
  "Deserializes a message object of type '<NavigateGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pos) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateGoal>)))
  "Returns string type for a message object of type '<NavigateGoal>"
  "move_quadcopter/NavigateGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateGoal)))
  "Returns string type for a message object of type 'NavigateGoal"
  "move_quadcopter/NavigateGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateGoal>)))
  "Returns md5sum for a message object of type '<NavigateGoal>"
  "332449a2fcdc11c82bafadb9df2b64d8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateGoal)))
  "Returns md5sum for a message object of type 'NavigateGoal"
  "332449a2fcdc11c82bafadb9df2b64d8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateGoal>)))
  "Returns full string definition for message of type '<NavigateGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal point for navigation action~%geometry_msgs/Point target_pos~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateGoal)))
  "Returns full string definition for message of type 'NavigateGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal point for navigation action~%geometry_msgs/Point target_pos~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pos))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateGoal
    (cl:cons ':target_pos (target_pos msg))
))
