; Auto-generated. Do not edit!


(cl:in-package move_quadcopter-msg)


;//! \htmlinclude NavigateFeedback.msg.html

(cl:defclass <NavigateFeedback> (roslisp-msg-protocol:ros-message)
  ((dist
    :reader dist
    :initarg :dist
    :type cl:float
    :initform 0.0))
)

(cl:defclass NavigateFeedback (<NavigateFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move_quadcopter-msg:<NavigateFeedback> is deprecated: use move_quadcopter-msg:NavigateFeedback instead.")))

(cl:ensure-generic-function 'dist-val :lambda-list '(m))
(cl:defmethod dist-val ((m <NavigateFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_quadcopter-msg:dist-val is deprecated.  Use move_quadcopter-msg:dist instead.")
  (dist m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateFeedback>) ostream)
  "Serializes a message object of type '<NavigateFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'dist))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateFeedback>) istream)
  "Deserializes a message object of type '<NavigateFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'dist) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateFeedback>)))
  "Returns string type for a message object of type '<NavigateFeedback>"
  "move_quadcopter/NavigateFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateFeedback)))
  "Returns string type for a message object of type 'NavigateFeedback"
  "move_quadcopter/NavigateFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateFeedback>)))
  "Returns md5sum for a message object of type '<NavigateFeedback>"
  "3f4fece6412db25720b2bab9f80b3473")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateFeedback)))
  "Returns md5sum for a message object of type 'NavigateFeedback"
  "3f4fece6412db25720b2bab9f80b3473")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateFeedback>)))
  "Returns full string definition for message of type '<NavigateFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# distance from goal is returned as feedback~%float64 dist~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateFeedback)))
  "Returns full string definition for message of type 'NavigateFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# distance from goal is returned as feedback~%float64 dist~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateFeedback
    (cl:cons ':dist (dist msg))
))
