; Auto-generated. Do not edit!


(cl:in-package move_quadcopter-msg)


;//! \htmlinclude NavigateActionGoal.msg.html

(cl:defclass <NavigateActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type move_quadcopter-msg:NavigateGoal
    :initform (cl:make-instance 'move_quadcopter-msg:NavigateGoal)))
)

(cl:defclass NavigateActionGoal (<NavigateActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move_quadcopter-msg:<NavigateActionGoal> is deprecated: use move_quadcopter-msg:NavigateActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <NavigateActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_quadcopter-msg:header-val is deprecated.  Use move_quadcopter-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <NavigateActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_quadcopter-msg:goal_id-val is deprecated.  Use move_quadcopter-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <NavigateActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_quadcopter-msg:goal-val is deprecated.  Use move_quadcopter-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateActionGoal>) ostream)
  "Serializes a message object of type '<NavigateActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateActionGoal>) istream)
  "Deserializes a message object of type '<NavigateActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateActionGoal>)))
  "Returns string type for a message object of type '<NavigateActionGoal>"
  "move_quadcopter/NavigateActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateActionGoal)))
  "Returns string type for a message object of type 'NavigateActionGoal"
  "move_quadcopter/NavigateActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateActionGoal>)))
  "Returns md5sum for a message object of type '<NavigateActionGoal>"
  "874aa85aa9d43c35964ab52ec13f53b8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateActionGoal)))
  "Returns md5sum for a message object of type 'NavigateActionGoal"
  "874aa85aa9d43c35964ab52ec13f53b8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateActionGoal>)))
  "Returns full string definition for message of type '<NavigateActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%NavigateGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: move_quadcopter/NavigateGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal point for navigation action~%geometry_msgs/Point target_pos~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateActionGoal)))
  "Returns full string definition for message of type 'NavigateActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%NavigateGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: move_quadcopter/NavigateGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal point for navigation action~%geometry_msgs/Point target_pos~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
