; Auto-generated. Do not edit!


(cl:in-package move_quadcopter-msg)


;//! \htmlinclude NavigateResult.msg.html

(cl:defclass <NavigateResult> (roslisp-msg-protocol:ros-message)
  ((reached_pos
    :reader reached_pos
    :initarg :reached_pos
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass NavigateResult (<NavigateResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move_quadcopter-msg:<NavigateResult> is deprecated: use move_quadcopter-msg:NavigateResult instead.")))

(cl:ensure-generic-function 'reached_pos-val :lambda-list '(m))
(cl:defmethod reached_pos-val ((m <NavigateResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_quadcopter-msg:reached_pos-val is deprecated.  Use move_quadcopter-msg:reached_pos instead.")
  (reached_pos m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateResult>) ostream)
  "Serializes a message object of type '<NavigateResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'reached_pos) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateResult>) istream)
  "Deserializes a message object of type '<NavigateResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'reached_pos) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateResult>)))
  "Returns string type for a message object of type '<NavigateResult>"
  "move_quadcopter/NavigateResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateResult)))
  "Returns string type for a message object of type 'NavigateResult"
  "move_quadcopter/NavigateResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateResult>)))
  "Returns md5sum for a message object of type '<NavigateResult>"
  "87b3721d96e4977c0d52e0b467b8784f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateResult)))
  "Returns md5sum for a message object of type 'NavigateResult"
  "87b3721d96e4977c0d52e0b467b8784f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateResult>)))
  "Returns full string definition for message of type '<NavigateResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# position reached by navigation after the action is finished~%geometry_msgs/Point reached_pos~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateResult)))
  "Returns full string definition for message of type 'NavigateResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# position reached by navigation after the action is finished~%geometry_msgs/Point reached_pos~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'reached_pos))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateResult>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateResult
    (cl:cons ':reached_pos (reached_pos msg))
))
