(cl:defpackage turtlesim_cleaner-srv
  (:use )
  (:export
   "MOVECIRCLE"
   "<MOVECIRCLE-REQUEST>"
   "MOVECIRCLE-REQUEST"
   "<MOVECIRCLE-RESPONSE>"
   "MOVECIRCLE-RESPONSE"
   "MOVESQUARE"
   "<MOVESQUARE-REQUEST>"
   "MOVESQUARE-REQUEST"
   "<MOVESQUARE-RESPONSE>"
   "MOVESQUARE-RESPONSE"
  ))

