// Auto-generated. Do not edit!

// (in-package move_quadcopter.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class NavigateResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.reached_pos = null;
    }
    else {
      if (initObj.hasOwnProperty('reached_pos')) {
        this.reached_pos = initObj.reached_pos
      }
      else {
        this.reached_pos = new geometry_msgs.msg.Point();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavigateResult
    // Serialize message field [reached_pos]
    bufferOffset = geometry_msgs.msg.Point.serialize(obj.reached_pos, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavigateResult
    let len;
    let data = new NavigateResult(null);
    // Deserialize message field [reached_pos]
    data.reached_pos = geometry_msgs.msg.Point.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 24;
  }

  static datatype() {
    // Returns string type for a message object
    return 'move_quadcopter/NavigateResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '87b3721d96e4977c0d52e0b467b8784f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # position reached by navigation after the action is finished
    geometry_msgs/Point reached_pos
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavigateResult(null);
    if (msg.reached_pos !== undefined) {
      resolved.reached_pos = geometry_msgs.msg.Point.Resolve(msg.reached_pos)
    }
    else {
      resolved.reached_pos = new geometry_msgs.msg.Point()
    }

    return resolved;
    }
};

module.exports = NavigateResult;
