// Generated by gencpp from file turtlesim_cleaner/MoveCircle.msg
// DO NOT EDIT!


#ifndef TURTLESIM_CLEANER_MESSAGE_MOVECIRCLE_H
#define TURTLESIM_CLEANER_MESSAGE_MOVECIRCLE_H

#include <ros/service_traits.h>


#include <turtlesim_cleaner/MoveCircleRequest.h>
#include <turtlesim_cleaner/MoveCircleResponse.h>


namespace turtlesim_cleaner
{

struct MoveCircle
{

typedef MoveCircleRequest Request;
typedef MoveCircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveCircle
} // namespace turtlesim_cleaner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim_cleaner::MoveCircle > {
  static const char* value()
  {
    return "6d766f6a2db01255c7ae96df4f8888c5";
  }

  static const char* value(const ::turtlesim_cleaner::MoveCircle&) { return value(); }
};

template<>
struct DataType< ::turtlesim_cleaner::MoveCircle > {
  static const char* value()
  {
    return "turtlesim_cleaner/MoveCircle";
  }

  static const char* value(const ::turtlesim_cleaner::MoveCircle&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim_cleaner::MoveCircleRequest> should match 
// service_traits::MD5Sum< ::turtlesim_cleaner::MoveCircle > 
template<>
struct MD5Sum< ::turtlesim_cleaner::MoveCircleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_cleaner::MoveCircle >::value();
  }
  static const char* value(const ::turtlesim_cleaner::MoveCircleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_cleaner::MoveCircleRequest> should match 
// service_traits::DataType< ::turtlesim_cleaner::MoveCircle > 
template<>
struct DataType< ::turtlesim_cleaner::MoveCircleRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim_cleaner::MoveCircle >::value();
  }
  static const char* value(const ::turtlesim_cleaner::MoveCircleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim_cleaner::MoveCircleResponse> should match 
// service_traits::MD5Sum< ::turtlesim_cleaner::MoveCircle > 
template<>
struct MD5Sum< ::turtlesim_cleaner::MoveCircleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_cleaner::MoveCircle >::value();
  }
  static const char* value(const ::turtlesim_cleaner::MoveCircleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_cleaner::MoveCircleResponse> should match 
// service_traits::DataType< ::turtlesim_cleaner::MoveCircle > 
template<>
struct DataType< ::turtlesim_cleaner::MoveCircleResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim_cleaner::MoveCircle >::value();
  }
  static const char* value(const ::turtlesim_cleaner::MoveCircleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_CLEANER_MESSAGE_MOVECIRCLE_H
